name: CI - Build y Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar el código
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restaurar dependencias
        run: dotnet restore

      - name: Compilar
        run: dotnet build --no-restore

      - name: Ejecutar Unit Tests
        run: dotnet test TurnosApi.Tests --no-build --logger "console;verbosity=detailed"

      - name: Ejecutar Integration Tests
        run: dotnet test TurnosApi.IntegrationTests --no-build --logger "console;verbosity=detailed"